version: "3.6"
services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - db-vol:/var/lib/mysql/
    restart: on-failure
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: server
      MYSQL_PASSWORD: qwertyuiop
      MYSQL_DATABASE: "store"
  server:
    build:
      dockerfile: ./docker/server/Dockerfile
      context: .
    command: node testdb.mjs
    restart: on-failure
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  db-vol: {}
