version: "3.6"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - db-vol:/var/lib/mysql/
    restart: on-failure
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: server
      MYSQL_PASSWORD: qwertyuiop
      MYSQL_DATABASE: "store"
  adminer:
    image: adminer
    restart: on-failure
    ports: 
      - 8081:8080
  server:
    build:
      dockerfile: ./docker/server/Dockerfile
      context: .
    command: node app.js
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db-vol: {}