version: "3.6"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - db-vol:/var/lib/mysql/
    restart: on-failure
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: testuser
      MYSQL_PASSWORD: qwertyuiop
      MYSQL_DATABASE: "store"
  adminer:
    image: adminer
    restart: on-failure
    ports: 
      - 8081:8080
volumes:
  db-vol: {}